Backend/src/Entity/JornadaLaboral.php
<?php

namespace App\Entity;

use App\Repository\JornadaLaboralRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: JornadaLaboralRepository::class)]
class JornadaLaboral
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'jornadaLaborals')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Profesor $profesor = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $dia = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $Inicio = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $Fin = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProfesor(): ?Profesor
    {
        return $this->profesor;
    }

    public function setProfesor(?Profesor $profesor): static
    {
        $this->profesor = $profesor;

        return $this;
    }
    #[Groups(['jornada'])]
    public function getDia(): ?\DateTimeInterface
    {
        return $this->dia;
    }

    public function setDia(\DateTimeInterface $dia): static
    {
        $this->dia = $dia;

        return $this;
    }
    #[Groups(['jornada'])]
    public function getInicio(): ?\DateTimeInterface
    {
        return $this->Inicio;
    }

    public function setInicio(\DateTimeInterface $Inicio): static
    {
        $this->Inicio = $Inicio;

        return $this;
    }
    #[Groups(['jornada'])]
    public function getFin(): ?\DateTimeInterface
    {
        return $this->Fin;
    }

    public function setFin(?\DateTimeInterface $Fin): static
    {
        $this->Fin = $Fin;

        return $this;
    }
}

Backend/src/Controller/PDFController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use App\Entity\Menu;
use App\Repository\MenuRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Clase;
use App\Repository\ClaseRepository;
use App\Entity\Profesor;
use App\Repository\ProfesorRepository;
use App\Entity\Usuario;
use App\Repository\UsuarioRepository;
use App\Entity\Alumno;
use App\Repository\AlumnoRepository;
use App\Entity\Asignatura;
use App\Repository\AsignaturaRepository;
use App\Entity\Aula;
use App\Repository\AulaRepository;
use App\Entity\Calificacion;
use App\Repository\CalificacionRepository;
use App\Entity\DiasSemana;
use App\Repository\DiasSemanaRepository;
use App\Entity\Mensaje;
use App\Repository\MensajeRepository;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\SerializerInterface;
use Symfony\Component\Serializer\Serializer;
use Symfony\Component\HttpFoundation\JsonResponse;
use App\Services\JwtAuth;
use App\Entity\Asistencia;
use App\Repository\AsistenciaRepository;
use App\Entity\JornadaLaboral;
use App\Repository\JornadaLaboralRepository;
use Dompdf\Dompdf;
use Dompdf\Options;

#[Route('/api/pdf', name: 'app_pdf')]
class PDFController extends AbstractController
{
    #[Route('/misnotas', name: 'app_misnotas_pdf', methods: ['GET'])]
    public function misNotasPdf(Request $request, JwtAuth $jwt_auth, AlumnoRepository $ar)
    {
        // Recoger token
        $token = $request->headers->get('Authorization');

        // Comprobar si es correcto
        $authCheck = $jwt_auth->checkToken($token);

        if ($authCheck) {
            $identity = $jwt_auth->checkToken($token, true);

            if ($identity->rol == 'alumno') {
                $alumnoId = $identity->id_alumno;
                $alumno = $ar->find($alumnoId);
                $notas = $alumno->getCalificacions();

                // Crear el contenido HTML para el PDF
                $html = $this->renderView('pdf/notas.html.twig', [
                    'notas' => $notas,
                    'alumno' => $alumno
                ]);

                // Configuración de Dompdf
                $options = new Options();
                $options->set('defaultFont', 'Arial');
                $options->set('isRemoteEnabled', true);
                $dompdf = new Dompdf($options);
                $dompdf->loadHtml($html);
                $dompdf->setPaper('A4', 'portrait');
                $dompdf->render();

                $output = $dompdf->output();

                return new Response($output, 200, [
                    'Content-Type' => 'application/pdf',
                    'Content-Disposition' => 'inline; filename="notas.pdf"',
                ]);
            }
        }

        return new JsonResponse([
            'status' => 'error',
            'code' => 400,
            'message' => 'No tienes permiso para realizar esta acción'
        ]);
    }

    #[Route('/misjornadas/{mes}', name: 'app_jornadas_pdf', methods: ['GET'])]
    public function misJornadas($mes, Request $request,JwtAuth $jwt_auth ,ProfesorRepository $pr, JornadaLaboralRepository $jr , SerializerInterface $serializer,EntityManagerInterface $em)
    {
        //Recoger token
        $token = $request->headers->get('Authorization');

        //Comprobar si es correcto
        $authCheck = $jwt_auth->checkToken($token);

        if($authCheck){
            $json = json_decode($request->getContent(), true);

            $identity = $jwt_auth->checkToken($token, true);
            
            if($identity->rol == 'profesor'){
                $profesorId = $identity->id_profesor;
                $profesor = $pr->find($profesorId);
                if($mes==0){
                    $jornadas = $jr->findBy(['profesor' => $pr->find($profesorId)]);
                }else{
                    $anio = date('Y'); 
                    $inicioMes = new \DateTime($anio . '-' . $mes . '-01');
                    $finMes = clone $inicioMes;
                    $finMes->modify('last day of this month');

                    $jornadas = $jr->createQueryBuilder('j')
                        ->where('j.profesor = :profesor')
                        ->andWhere('j.dia BETWEEN :inicioMes AND :finMes')
                        ->setParameter('profesor', $profesor)
                        ->setParameter('inicioMes', $inicioMes)
                        ->setParameter('finMes', $finMes)
                        ->getQuery()
                        ->getResult();
                }

                }
                // Crear el contenido HTML para el PDF
                $html = $this->renderView('pdf/jornadas.html.twig', [
                'jornadas' => $jornadas,
                'profesor' => $profesor
                ]);

                // Configuración de Dompdf
                $options = new Options();
                $options->set('defaultFont', 'Arial');
                $options->set('isRemoteEnabled', true);
                $dompdf = new Dompdf($options);
                $dompdf->loadHtml($html);
                $dompdf->setPaper('A4', 'portrait');
                $dompdf->render();

                $output = $dompdf->output();

                return new Response($output, 200, [
                    'Content-Type' => 'application/pdf',
                    'Content-Disposition' => 'inline; filename="jornadas.pdf"',
                ]);
            }
        

        return new JsonResponse([
            'status' => 'error',
            'code' => 400,
            'message' => 'No tienes permiso para realizar esta acción'
        ]);
    }
}

Backend/templates/pdf/jornadas.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Jornadas Laborales del Profesor</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        table, th, td {
            border: 1px solid black;
        }
        th, td {
            padding: 10px;
            text-align: left;
        }
        th {
            background-color: #A6BDA9;
        }
        .footer {
            width: 100%;
            text-align: center;
            position: fixed;
            bottom: 0px;
            font-size: 12px;
        }
        .pagenum:before {
            content: counter(page);
        }
    </style>
</head>
<body>
    <h1>MYACADEMY MANAGER</h1>
    <h3>Jornadas de {{ profesor.usuario.nombre }} {{profesor.usuario.apellidos}}</h3>
    <h3>ID de Profesor: {{ profesor.id }}</h3>
    <table>
        <thead>
            <tr>
                <th>Dia</th>
                <th>Hora Inicio</th>
                <th>Hora Fin</th>
            </tr>
        </thead>
        <tbody>
            {% for j in jornadas %}
                <tr>
                    <td>{{ j.dia|date('d-m-Y') }}</td>
                    <td>{{ j.inicio|date('H:i:s') }}</td>
                    <td>{{ j.fin|date('H:i:s') }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
     <div class="footer">
        <p>Informe generado por MyAcademy Manager: {{ "now" | date("d-m-Y H:i") }}</p>
        <p>Página <span class="pagenum"></span></p>
    </div>
</body>
</html>

Backend/templates/pdf/notas.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Notas del Alumno</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        table, th, td {
            border: 1px solid black;
        }
        th, td {
            padding: 10px;
            text-align: left;
        }
        th {
            background-color: #A6BDA9;
        }
        .footer {
            width: 100%;
            text-align: center;
            position: fixed;
            bottom: 0px;
            font-size: 12px;
        }
        .pagenum:before {
            content: counter(page);
        }
    </style>
</head>
<body>
    <h1>MYACADEMY MANAGER</h1>
    <h3>Notas de {{ alumno.usuario.nombre }} {{alumno.usuario.apellidos}}</h3>
    <h3>ID de Alumno: {{ alumno.id }}</h3>
    <table>
        <thead>
            <tr>
                <th>Asignatura</th>
                <th>Nota</th>
            </tr>
        </thead>
        <tbody>
            {% for nota in notas %}
                <tr>
                    <td>{{ nota.clase.asignatura.nombre }}</td>
                    <td>{{ nota.nota }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
     <div class="footer">
        <p>Informe generado por MyAcademy Manager: {{ "now" | date("d-m-Y H:i") }}</p>
        <p>Página <span class="pagenum"></span></p>
    </div>
</body>
</html>